---
- name: Now let's interop with Ansible native modules
  hosts: dist-sw01
  gather_facts: no

  vars:
    username: "developer"
    password: "C1sco12345"
    url: "https://10.10.20.49:443/jsonrpc"
    perform_backup: no

  tasks:

    - name: Direct device change
      nxos_vlans:
        config:
          - vlan_id: 501
            name: ansible
        state:  merged
      register: r_vlan
 
    - debug: 
        var: r_vlan

    - name: Check Sync for one device
      nso_action:
        username: "{{ username }}"
        password: "{{ password }}"
        url: "{{ url }}"
        path: /ncs:devices/check-sync
        input: { 'device': [ "{{ inventory_hostname }}" ] }
      changed_when: False
      register: r_sync

    - debug: 
        var: r_sync

    - name: Sync from one device
      nso_action:
        username: "{{ username }}"
        password: "{{ password }}"
        url: "{{ url }}"
        path: /ncs:devices/sync-from
        input: { 'device': [ "{{ inventory_hostname }}" ] }
      changed_when: False
      register: r_sync

    - debug:
        var: r_sync

    - name: Check Sync for one device
      nso_action:
        username: "{{ username }}"
        password: "{{ password }}"
        url: "{{ url }}"
        path: /ncs:devices/check-sync
        input: { 'device': [ "{{ inventory_hostname }}" ] }
      changed_when: False
      register: r_sync


