- name: Some NSO fun
  hosts: localhost
  gather_facts: no

  vars:
    username: "developer"
    password: "C1sco12345"
    url: "https://10.10.20.49:443/jsonrpc"
    perform_backup: no


  tasks: 

    - name: Sync to a specific device
      nso_action:
        username: "{{ username }}"
        password: "{{ password }}"
        url: "{{ url }}"
        path: /ncs:devices/sync-to
        input: { "device": ["{{ target }}"] }
      changed_when: False
      register: r_sync

    - debug:
        var: r_sync
